
import java.awt.print.PrinterException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Iterator;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class PrintRecord extends javax.swing.JFrame {

    /**
     * Creates new form PrintRecord
     */
    public PrintRecord() {
        initComponents();
        this.setTitle("Print a Record");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jDesktopPane4 = new javax.swing.JDesktopPane();
        jButton2 = new javax.swing.JButton();
        jDesktopPane5 = new javax.swing.JDesktopPane();
        jButton6 = new javax.swing.JButton();
        jDesktopPane6 = new javax.swing.JDesktopPane();
        jButton4 = new javax.swing.JButton();
        jDesktopPane7 = new javax.swing.JDesktopPane();
        jButton3 = new javax.swing.JButton();
        jDesktopPane8 = new javax.swing.JDesktopPane();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("         PRINT RECORDS OF BOOK ISSUED AND RETURNED IN LIBRARY ");

        jDesktopPane2.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/li/read.png"))); // NOI18N
        jButton1.setText("Read a File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jDesktopPane3.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/li/write.png"))); // NOI18N
        jButton2.setText("Write Return books");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jDesktopPane4.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane4Layout = new javax.swing.GroupLayout(jDesktopPane4);
        jDesktopPane4.setLayout(jDesktopPane4Layout);
        jDesktopPane4Layout.setHorizontalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane4Layout.setVerticalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setText("Write Book Stock list");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jDesktopPane5.setLayer(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane5Layout = new javax.swing.GroupLayout(jDesktopPane5);
        jDesktopPane5.setLayout(jDesktopPane5Layout);
        jDesktopPane5Layout.setHorizontalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane5Layout.setVerticalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/li/back.png"))); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jDesktopPane6.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane6Layout = new javax.swing.GroupLayout(jDesktopPane6);
        jDesktopPane6.setLayout(jDesktopPane6Layout);
        jDesktopPane6Layout.setHorizontalGroup(
            jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane6Layout.setVerticalGroup(
            jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Write Issued Books");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jDesktopPane7.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane7Layout = new javax.swing.GroupLayout(jDesktopPane7);
        jDesktopPane7.setLayout(jDesktopPane7Layout);
        jDesktopPane7Layout.setHorizontalGroup(
            jDesktopPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane7Layout.setVerticalGroup(
            jDesktopPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/li/print.png"))); // NOI18N
        jButton5.setText("Print");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jDesktopPane8.setLayer(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane8Layout = new javax.swing.GroupLayout(jDesktopPane8);
        jDesktopPane8.setLayout(jDesktopPane8Layout);
        jDesktopPane8Layout.setHorizontalGroup(
            jDesktopPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane8Layout.setVerticalGroup(
            jDesktopPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane3)
                    .addComponent(jDesktopPane4)
                    .addComponent(jDesktopPane5)
                    .addComponent(jDesktopPane7)
                    .addComponent(jDesktopPane6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDesktopPane8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addComponent(jDesktopPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDesktopPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDesktopPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDesktopPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDesktopPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDesktopPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDesktopPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDesktopPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          Connection con = null;
          ResultSet rs = null;
          
            Statement smt =null; 
          ArrayList data = new ArrayList();
         
              try{
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                     con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","library","pdc");
                   smt=con.createStatement();
                   rs = smt.executeQuery("Select * from issuereturn");
                   ResultSetMetaData rsmd=rs.getMetaData();
                   String cbookid=rsmd.getColumnName(1);
                   String cnameofbook =rsmd.getColumnName(2);
                    String cauthor =rsmd.getColumnName(3);
                     String cissuedate =rsmd.getColumnName(4);
                      String cdate =rsmd.getColumnName(5);
                       String cyear =rsmd.getColumnName(6);
                        String csemester =rsmd.getColumnName(7);
                         String cstudentname =rsmd.getColumnName(8);
                          String cstudentid =rsmd.getColumnName(9);
                 data.add(cbookid+ "," + cnameofbook + "," + cauthor + "," + cissuedate+","+cdate+","+cyear+","+csemester+","+cstudentname+","+cstudentid);

                     while(rs.next()) {
                           String bookid= rs.getString(1);
                           String nameofbook=rs.getString(2);
                           String author=rs.getString(3);
                           String issuedate=rs.getString(4);
                           Date date=rs.getDate(5);
                           String year=rs.getString(6);
                           String semester=rs.getString(7);
                           String studentname=rs.getString(8);
                           String studentid=rs.getString(9);
  data.add(bookid+ "," + nameofbook + "," + author + "," + issuedate+","+date+","+year+","+semester+","+studentname+","+studentid);
                     }    
                
                       // System.out.println(data);
               JOptionPane.showMessageDialog(null,"Done writing","infromation",JOptionPane.INFORMATION_MESSAGE);
                         Iterator i=data.listIterator();
                          FileOutputStream fis=new FileOutputStream("studentrecords.csv");
              try (PrintWriter pw = new PrintWriter(fis)) {
                 
                  pw.append("\n");
                     
                  while(i.hasNext())
                  {
                      
                      pw.append((CharSequence)i.next());
                      pw.append("\n");
                  
                  }
                 pw.close();
                  JOptionPane.showMessageDialog(null,"Done completed","infromation",JOptionPane.INFORMATION_MESSAGE);
              }
        
    }  
            
                     catch (FileNotFoundException ex) {
            Logger.getLogger(PrintRecord.class.getName()).log(Level.SEVERE, null, ex);
        }
              
              catch(ClassNotFoundException | SQLException e)
              {
                 JOptionPane.showMessageDialog(null, e);  
              }
              
       
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         try
        {
            boolean complete=jTextArea1.print();
            if(complete)
            {
              JOptionPane.showMessageDialog(null,"Done printing","infromation",JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"printing!","printer",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(PrinterException e)
        {
         JOptionPane.showMessageDialog(null, e);   
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        AferLogin al=new AferLogin();
        al.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
           Connection con = null;
          ResultSet rs = null;
          
          
            Statement smt =null; 
          ArrayList data = new ArrayList();
              try{
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                     con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","library","pdc");
                   smt=con.createStatement();
                   rs = smt.executeQuery("Select * from issuebook");
                    ResultSetMetaData  rsmd=rs.getMetaData();
                    String cbookid=rsmd.getColumnName(1);
                     String cnameofbook=rsmd.getColumnName(2);
                      String cauthor=rsmd.getColumnName(3);
                       String cissuedate=rsmd.getColumnName(4);
                        String cstudentname=rsmd.getColumnName(5);
                         String cstudentid=rsmd.getColumnName(6);
                          String cyear=rsmd.getColumnName(7);
                           String csemester=rsmd.getColumnName(8);
                            String ccourse=rsmd.getColumnName(9);
      data.add(cbookid+ "," + cnameofbook + "," + cauthor + "," + cissuedate+","+cstudentname+","+cstudentid+","+cyear+","+csemester+","+ccourse+",");

                     while(rs.next()) {
                           String bookid= rs.getString(1);
                           String nameofbook=rs.getString(2);
                           String author=rs.getString(3);
                           String issuedate=rs.getString(4);
                           String studentname=rs.getString(5);
                           String studentid=rs.getString(6);
                           String year=rs.getString(7);
                           String semester=rs.getString(8);
                           String course=rs.getString(9);
                           data.add(bookid+ "," + nameofbook + "," + author + "," + issuedate+","+studentname+","+studentid+","+year+","+semester+","+course+",");
                           //writeToFile(data, "student.txt");
                     }    
                
                       // System.out.println(data);
               JOptionPane.showMessageDialog(null,"Done writing","infromation",JOptionPane.INFORMATION_MESSAGE);
         //  String sss='"+bookid+'",nameofbook,author,issuedate,date,year,semester,studentname,studentid\n";     
                         Iterator i=data.listIterator();
                          FileOutputStream fis=new FileOutputStream("studentissueddetails.csv");
              try (PrintWriter pw = new PrintWriter(fis)) {
                  while(i.hasNext())
                  {
                      
                      pw.append((CharSequence)i.next());
                      pw.append("\n");
                  
                  }
                 pw.close();
                  JOptionPane.showMessageDialog(null,"Done completed","infromation",JOptionPane.INFORMATION_MESSAGE);
              }
              }
                           
                     catch (FileNotFoundException ex) {
            Logger.getLogger(PrintRecord.class.getName()).log(Level.SEVERE, null, ex);
        }
              
              catch(ClassNotFoundException | SQLException e)
              {
                 JOptionPane.showMessageDialog(null, e);  
              }
             
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            JFileChooser chooser = new JFileChooser();
            int returnVal = chooser.showOpenDialog(null); //replace null with your swing container
            File file = null;
            if(returnVal == JFileChooser.APPROVE_OPTION)
            file = chooser.getSelectedFile();
            BufferedReader in = null;
            try {
                in = new BufferedReader(new FileReader(file));
            } catch (FileNotFoundException ex) {
                //Logger.getLogger(print.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);
            }
            String line = null;
            try {
                line = in.readLine();
            } catch (IOException | NullPointerException ex) {
                // Logger.getLogger(print.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);
            }
            while(line != null){
                jTextArea1.append(line + "\n");
                try {
                    line = in.readLine();
                } catch (IOException ex) {
                    //  Logger.getLogger(print.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null,ex);
                }
            }
        }
        catch(NullPointerException npe)
        {
            JOptionPane.showMessageDialog(null, npe);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
           Connection con = null;
          ResultSet rs = null;
        
            Statement smt =null; 
          ArrayList data = new ArrayList();
              try{
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                     con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","library","pdc");
                   smt=con.createStatement();
                   rs = smt.executeQuery("Select * from addbook");
                     ResultSetMetaData  rsmd=rs.getMetaData();
                      String cbookid=null;
                           String cnameofbook=null;
                           String cedition=null;
                           String cpublisher=null;
                           String cprice=null;
                           String cpage=null;
                           cbookid=rsmd.getColumnName(1);
                           cnameofbook=rsmd.getColumnName(2);
                           cedition=rsmd.getColumnName(3);
                           cpublisher=rsmd.getColumnName(4);
                           cprice=rsmd.getColumnName(5);
                           cpage=rsmd.getColumnName(6);
                            data.add(cbookid+ "," + cnameofbook + "," + cedition + "," + cpublisher+","+cprice+","+cpage+",");
                     while(rs.next()) {
                           String bookid= rs.getString(1);
                           String nameofbook=rs.getString(2);
                           String edition=rs.getString(3);
                           String publisher=rs.getString(4);
                           String price=rs.getString(5);
                           String pages=rs.getString(6);
                          data.add(bookid+ "," + nameofbook + "," + edition + "," + publisher+","+price+","+pages+",");
                        
                     }  
                     
               JOptionPane.showMessageDialog(null,"Done writing","infromation",JOptionPane.INFORMATION_MESSAGE);
                         Iterator i=data.listIterator();
                          FileOutputStream fis=new FileOutputStream("booklist.csv");
              try (PrintWriter pw = new PrintWriter(fis)) {
                  while(i.hasNext())
                  {
                      
                      pw.append((CharSequence)i.next());
                      pw.append("\n");
                  
                  }
                 pw.close();
                  JOptionPane.showMessageDialog(null,"Done completed","infromation",JOptionPane.INFORMATION_MESSAGE);
              }
              }
                           
                     catch (FileNotFoundException ex) {
            Logger.getLogger(PrintRecord.class.getName()).log(Level.SEVERE, null, ex);
        }
              
              catch(ClassNotFoundException | SQLException e)
              {
                 JOptionPane.showMessageDialog(null, e);  
              }
             
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JDesktopPane jDesktopPane5;
    private javax.swing.JDesktopPane jDesktopPane6;
    private javax.swing.JDesktopPane jDesktopPane7;
    private javax.swing.JDesktopPane jDesktopPane8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
